name: run terraform

on:
  push:
    branches: [ master ]

jobs:    
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      TF_VAR_db_password: ${{ secrets.TF_VAR_DB_PASSWORD }}

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init for postgres_rds
      run: terraform init -input=false
      working-directory: "pyspark-cdc/terraform/postgres_rds"
    
    - name: Terraform Plan for postgres_rds
      run: terraform plan -input=false
      working-directory: "pyspark-cdc/terraform/postgres_rds"

    - name: Terraform Init for s3_bucket
      run: terraform init -input=false
      working-directory: "pyspark-cdc/terraform/s3_bucket"
    
    - name: Terraform Plan for s3_bucket
      run: terraform plan -input=false
      working-directory: "pyspark-cdc/terraform/s3_bucket"

    - name: Terraform Init for DMS replication instance
      run: terraform init -input=false
      working-directory: "pyspark-cdc/terraform/data_migration_services"

    - name: Terraform Plan for DMS replication instance
      run: terraform plan -input=false
      working-directory: "pyspark-cdc/terraform/data_migration_services"
