# name: run terraform

# on:
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]

# jobs:    
#   init:
#     runs-on: ubuntu-latest
#     env:
#       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#       AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

#     steps:
#     - name: Checkout Repo
#       uses: actions/checkout@v3

#     - name: Setup Terraform
#       uses: hashicorp/setup-terraform@v2

#     - name: Terraform Init
#       run: terraform init -input=false
#       working-directory: "pyspark-cdc/terraform/postgres_rds"
    
#     - name: Terraform Plan
#       run: terraform plan -input=false
#       working-directory: "pyspark-cdc/terraform/postgres_rds"
